{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "78d8babc",
   "metadata": {
    "papermill": {
     "duration": 0.009139,
     "end_time": "2024-07-14T07:42:06.208031",
     "exception": false,
     "start_time": "2024-07-14T07:42:06.198892",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Tech Layoffs Data Cleaning in SQL\n",
    "\n",
    "I have copied this notework **[Tech Layoffs Data Cleaning in SQL] (https://www.kaggle.com/code/wilfridawere/tech-layoffs-data-cleaning-in-sql)** and take it as a starting point for a SQL exercise. The original notebook used *SQL (sqlite3)* to clean a dataset I put on Kaggle **[Tech layoffs 2020 - 2024](https://www.kaggle.com/datasets/ulrikeherold/tech-layoffs-2020-2024)** but a updated version. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "da64fd97",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:06.227278Z",
     "iopub.status.busy": "2024-07-14T07:42:06.226799Z",
     "iopub.status.idle": "2024-07-14T07:42:07.410126Z",
     "shell.execute_reply": "2024-07-14T07:42:07.408682Z"
    },
    "papermill": {
     "duration": 1.196622,
     "end_time": "2024-07-14T07:42:07.413368",
     "exception": false,
     "start_time": "2024-07-14T07:42:06.216746",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import sqlite3 # for using SQL commands"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a57a437a",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.432261Z",
     "iopub.status.busy": "2024-07-14T07:42:07.431610Z",
     "iopub.status.idle": "2024-07-14T07:42:07.515112Z",
     "shell.execute_reply": "2024-07-14T07:42:07.513460Z"
    },
    "papermill": {
     "duration": 0.096857,
     "end_time": "2024-07-14T07:42:07.518599",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.421742",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>#</th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Region</th>\n",
       "      <th>State</th>\n",
       "      <th>Country</th>\n",
       "      <th>Continent</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Percentage</th>\n",
       "      <th>Company_Size_before_Layoffs</th>\n",
       "      <th>Company_Size_after_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "      <th>Stage</th>\n",
       "      <th>Money_Raised_in__mil</th>\n",
       "      <th>Year</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Tamara Mellon</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>NaN</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>20.0</td>\n",
       "      <td>2020-03-12</td>\n",
       "      <td>40,0</td>\n",
       "      <td>50</td>\n",
       "      <td>30</td>\n",
       "      <td>Retail</td>\n",
       "      <td>Series C</td>\n",
       "      <td>90.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>HopSkipDrive</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>NaN</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>10,0</td>\n",
       "      <td>80</td>\n",
       "      <td>72</td>\n",
       "      <td>Transportation</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>45.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Panda Squad</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>San Francisco Bay Area</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>75,0</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>Consumer</td>\n",
       "      <td>Seed</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>37.779259</td>\n",
       "      <td>-122.419329</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Help.com</td>\n",
       "      <td>Austin</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>16.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>100,0</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>Support</td>\n",
       "      <td>Seed</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>30.271129</td>\n",
       "      <td>-97.743700</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Inspirato</td>\n",
       "      <td>Denver</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>130.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>22,0</td>\n",
       "      <td>591</td>\n",
       "      <td>461</td>\n",
       "      <td>Travel</td>\n",
       "      <td>Series C</td>\n",
       "      <td>79.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>39.739236</td>\n",
       "      <td>-104.984862</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   #        Company    Location_HQ                  Region       State  \\\n",
       "0  1  Tamara Mellon    Los Angeles                     NaN  California   \n",
       "1  2   HopSkipDrive    Los Angeles                     NaN  California   \n",
       "2  3    Panda Squad  San Francisco  San Francisco Bay Area  California   \n",
       "3  4       Help.com         Austin                     NaN         NaN   \n",
       "4  5      Inspirato         Denver                     NaN         NaN   \n",
       "\n",
       "  Country      Continent  Laid_Off Date_layoffs Percentage  \\\n",
       "0     USA  North America      20.0   2020-03-12       40,0   \n",
       "1     USA  North America       8.0   2020-03-13       10,0   \n",
       "2     USA  North America       6.0   2020-03-13       75,0   \n",
       "3     USA  North America      16.0   2020-03-16      100,0   \n",
       "4     USA  North America     130.0   2020-03-16       22,0   \n",
       "\n",
       "  Company_Size_before_Layoffs Company_Size_after_layoffs        Industry  \\\n",
       "0                         50                         30           Retail   \n",
       "1                         80                         72   Transportation   \n",
       "2                          8                          2         Consumer   \n",
       "3                         16                          0          Support   \n",
       "4                        591                        461           Travel   \n",
       "\n",
       "      Stage  Money_Raised_in__mil  Year   latitude   longitude  \n",
       "0  Series C                  90.0  2020  34.053691 -118.242766  \n",
       "1   Unknown                  45.0  2020  34.053691 -118.242766  \n",
       "2      Seed                   1.0  2020  37.779259 -122.419329  \n",
       "3      Seed                   6.0  2020  30.271129  -97.743700  \n",
       "4  Series C                  79.0  2020  39.739236 -104.984862  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Load the data\n",
    "tech_layoffs = pd.read_csv('/kaggle/input/tech-layoffs-2020-2024/tech_layoffs_Q2_2024.csv')\n",
    "df = tech_layoffs.copy() # make a copy\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "180d1dea",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.539534Z",
     "iopub.status.busy": "2024-07-14T07:42:07.539011Z",
     "iopub.status.idle": "2024-07-14T07:42:07.571350Z",
     "shell.execute_reply": "2024-07-14T07:42:07.569782Z"
    },
    "papermill": {
     "duration": 0.04694,
     "end_time": "2024-07-14T07:42:07.574817",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.527877",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1839 entries, 0 to 1838\n",
      "Data columns (total 18 columns):\n",
      " #   Column                       Non-Null Count  Dtype  \n",
      "---  ------                       --------------  -----  \n",
      " 0   #                            1839 non-null   int64  \n",
      " 1   Company                      1839 non-null   object \n",
      " 2   Location_HQ                  1839 non-null   object \n",
      " 3   Region                       473 non-null    object \n",
      " 4   State                        566 non-null    object \n",
      " 5   Country                      1839 non-null   object \n",
      " 6   Continent                    1839 non-null   object \n",
      " 7   Laid_Off                     1677 non-null   float64\n",
      " 8   Date_layoffs                 1839 non-null   object \n",
      " 9   Percentage                   1667 non-null   object \n",
      " 10  Company_Size_before_Layoffs  1585 non-null   object \n",
      " 11  Company_Size_after_layoffs   1619 non-null   object \n",
      " 12  Industry                     1839 non-null   object \n",
      " 13  Stage                        1839 non-null   object \n",
      " 14  Money_Raised_in__mil         1692 non-null   float64\n",
      " 15  Year                         1839 non-null   int64  \n",
      " 16  latitude                     1839 non-null   float64\n",
      " 17  longitude                    1839 non-null   float64\n",
      "dtypes: float64(4), int64(2), object(12)\n",
      "memory usage: 258.7+ KB\n"
     ]
    }
   ],
   "source": [
    "df.info()  # 1839 rows and 18 columns"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f34956f4",
   "metadata": {
    "papermill": {
     "duration": 0.009023,
     "end_time": "2024-07-14T07:42:07.592705",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.583682",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "The columns `Laid_Off`, `Percentage`, `Company_Size_before_Layoffs`, `Company_Size_after_layoffs` have missing values so I will inspect them. This helps decide whether to impute or drop those rows with missing values. I don't need the `Money_Raised_in_$_mil` column"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a955ba35",
   "metadata": {
    "papermill": {
     "duration": 0.008302,
     "end_time": "2024-07-14T07:42:07.609859",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.601557",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Connect to a Database and convert the Dataframe to a Table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "444888a0",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.630406Z",
     "iopub.status.busy": "2024-07-14T07:42:07.629532Z",
     "iopub.status.idle": "2024-07-14T07:42:07.635403Z",
     "shell.execute_reply": "2024-07-14T07:42:07.634047Z"
    },
    "papermill": {
     "duration": 0.01953,
     "end_time": "2024-07-14T07:42:07.638200",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.618670",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Connect to the database\n",
    "conn = sqlite3.connect('tech_layoffs_data.db')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "898b1120",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.658726Z",
     "iopub.status.busy": "2024-07-14T07:42:07.657386Z",
     "iopub.status.idle": "2024-07-14T07:42:07.720635Z",
     "shell.execute_reply": "2024-07-14T07:42:07.718659Z"
    },
    "papermill": {
     "duration": 0.077092,
     "end_time": "2024-07-14T07:42:07.724198",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.647106",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Table 'tech_layoffs' created and data loaded successfully.\n"
     ]
    }
   ],
   "source": [
    "# Create 'tech_layoffs' table\n",
    "cursor = conn.cursor()\n",
    "cursor.execute(\"SELECT name FROM sqlite_master WHERE type='table' AND name='tech_layoffs'\")\n",
    "table_exists = len(cursor.fetchall()) > 0\n",
    "\n",
    "if not table_exists:\n",
    "  # Load data to 'tech_layoffs' table only if it doesn't exist\n",
    "  df.to_sql('tech_layoffs', conn, index=False)\n",
    "  print(\"Table 'tech_layoffs' created and data loaded successfully.\")\n",
    "else:\n",
    "  print(\"Table 'tech_layoffs' already exists. Skipping data loading.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "0bc27f40",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.744978Z",
     "iopub.status.busy": "2024-07-14T07:42:07.744482Z",
     "iopub.status.idle": "2024-07-14T07:42:07.780411Z",
     "shell.execute_reply": "2024-07-14T07:42:07.778864Z"
    },
    "papermill": {
     "duration": 0.049655,
     "end_time": "2024-07-14T07:42:07.783319",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.733664",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>#</th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Region</th>\n",
       "      <th>State</th>\n",
       "      <th>Country</th>\n",
       "      <th>Continent</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Percentage</th>\n",
       "      <th>Company_Size_before_Layoffs</th>\n",
       "      <th>Company_Size_after_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "      <th>Stage</th>\n",
       "      <th>Money_Raised_in__mil</th>\n",
       "      <th>Year</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Tamara Mellon</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>None</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>20.0</td>\n",
       "      <td>2020-03-12</td>\n",
       "      <td>40,0</td>\n",
       "      <td>50</td>\n",
       "      <td>30</td>\n",
       "      <td>Retail</td>\n",
       "      <td>Series C</td>\n",
       "      <td>90.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>HopSkipDrive</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>None</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>10,0</td>\n",
       "      <td>80</td>\n",
       "      <td>72</td>\n",
       "      <td>Transportation</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>45.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Panda Squad</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>San Francisco Bay Area</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>75,0</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>Consumer</td>\n",
       "      <td>Seed</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>37.779259</td>\n",
       "      <td>-122.419329</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Help.com</td>\n",
       "      <td>Austin</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>16.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>100,0</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>Support</td>\n",
       "      <td>Seed</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>30.271129</td>\n",
       "      <td>-97.743700</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Inspirato</td>\n",
       "      <td>Denver</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>130.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>22,0</td>\n",
       "      <td>591</td>\n",
       "      <td>461</td>\n",
       "      <td>Travel</td>\n",
       "      <td>Series C</td>\n",
       "      <td>79.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>39.739236</td>\n",
       "      <td>-104.984862</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>Flytedesk</td>\n",
       "      <td>Boulder</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2020-03-18</td>\n",
       "      <td>20,0</td>\n",
       "      <td>20</td>\n",
       "      <td>16</td>\n",
       "      <td>Marketing</td>\n",
       "      <td>Seed</td>\n",
       "      <td>4.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>40.014986</td>\n",
       "      <td>-105.270545</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>7</td>\n",
       "      <td>Remote Year</td>\n",
       "      <td>Chicago</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>50.0</td>\n",
       "      <td>2020-03-19</td>\n",
       "      <td>50,0</td>\n",
       "      <td>100</td>\n",
       "      <td>50</td>\n",
       "      <td>Travel</td>\n",
       "      <td>Series B</td>\n",
       "      <td>17.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>41.875562</td>\n",
       "      <td>-87.624421</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8</td>\n",
       "      <td>CTO.ai</td>\n",
       "      <td>Vancouver</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>Canada</td>\n",
       "      <td>North America</td>\n",
       "      <td>30.0</td>\n",
       "      <td>2020-03-20</td>\n",
       "      <td>50,0</td>\n",
       "      <td>60</td>\n",
       "      <td>30</td>\n",
       "      <td>Infrastructure</td>\n",
       "      <td>Seed</td>\n",
       "      <td>7.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>49.260872</td>\n",
       "      <td>-123.113952</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>9</td>\n",
       "      <td>Flywheel Sports</td>\n",
       "      <td>New York City</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>784.0</td>\n",
       "      <td>2020-03-20</td>\n",
       "      <td>98,0</td>\n",
       "      <td>800</td>\n",
       "      <td>16</td>\n",
       "      <td>Fitness</td>\n",
       "      <td>Acquired</td>\n",
       "      <td>120.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>40.712728</td>\n",
       "      <td>-74.006015</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10</td>\n",
       "      <td>Compass</td>\n",
       "      <td>New York City</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>375.0</td>\n",
       "      <td>2020-03-23</td>\n",
       "      <td>15,0</td>\n",
       "      <td>2500</td>\n",
       "      <td>2125</td>\n",
       "      <td>Real Estate</td>\n",
       "      <td>Series G</td>\n",
       "      <td>1600.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>40.712728</td>\n",
       "      <td>-74.006015</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    #          Company    Location_HQ                  Region       State  \\\n",
       "0   1    Tamara Mellon    Los Angeles                    None  California   \n",
       "1   2     HopSkipDrive    Los Angeles                    None  California   \n",
       "2   3      Panda Squad  San Francisco  San Francisco Bay Area  California   \n",
       "3   4         Help.com         Austin                    None        None   \n",
       "4   5        Inspirato         Denver                    None        None   \n",
       "5   6        Flytedesk        Boulder                    None        None   \n",
       "6   7      Remote Year        Chicago                    None        None   \n",
       "7   8           CTO.ai      Vancouver                    None        None   \n",
       "8   9  Flywheel Sports  New York City                    None        None   \n",
       "9  10          Compass  New York City                    None        None   \n",
       "\n",
       "  Country      Continent  Laid_Off Date_layoffs Percentage  \\\n",
       "0     USA  North America      20.0   2020-03-12       40,0   \n",
       "1     USA  North America       8.0   2020-03-13       10,0   \n",
       "2     USA  North America       6.0   2020-03-13       75,0   \n",
       "3     USA  North America      16.0   2020-03-16      100,0   \n",
       "4     USA  North America     130.0   2020-03-16       22,0   \n",
       "5     USA  North America       4.0   2020-03-18       20,0   \n",
       "6     USA  North America      50.0   2020-03-19       50,0   \n",
       "7  Canada  North America      30.0   2020-03-20       50,0   \n",
       "8     USA  North America     784.0   2020-03-20       98,0   \n",
       "9     USA  North America     375.0   2020-03-23       15,0   \n",
       "\n",
       "  Company_Size_before_Layoffs Company_Size_after_layoffs        Industry  \\\n",
       "0                         50                         30           Retail   \n",
       "1                         80                         72   Transportation   \n",
       "2                          8                          2         Consumer   \n",
       "3                         16                          0          Support   \n",
       "4                        591                        461           Travel   \n",
       "5                         20                         16        Marketing   \n",
       "6                        100                         50           Travel   \n",
       "7                         60                         30   Infrastructure   \n",
       "8                        800                         16          Fitness   \n",
       "9                       2500                       2125      Real Estate   \n",
       "\n",
       "      Stage  Money_Raised_in__mil  Year   latitude   longitude  \n",
       "0  Series C                  90.0  2020  34.053691 -118.242766  \n",
       "1   Unknown                  45.0  2020  34.053691 -118.242766  \n",
       "2      Seed                   1.0  2020  37.779259 -122.419329  \n",
       "3      Seed                   6.0  2020  30.271129  -97.743700  \n",
       "4  Series C                  79.0  2020  39.739236 -104.984862  \n",
       "5      Seed                   4.0  2020  40.014986 -105.270545  \n",
       "6  Series B                  17.0  2020  41.875562  -87.624421  \n",
       "7      Seed                   7.0  2020  49.260872 -123.113952  \n",
       "8  Acquired                 120.0  2020  40.712728  -74.006015  \n",
       "9  Series G                1600.0  2020  40.712728  -74.006015  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Now I will use SQL commands to Clean data from the 'tech_layoffs' table\n",
    "# pd.read_sql_query is an optimized approach for working with pandas and sqlite3\n",
    "\n",
    "# Inspect the first_10_rows\n",
    "first_10_rows = pd.read_sql_query(\"\"\"SELECT *\n",
    "                                   FROM tech_layoffs\n",
    "                                   LIMIT 10;\"\"\", conn)\n",
    "first_10_rows"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a0fa976",
   "metadata": {
    "papermill": {
     "duration": 0.009512,
     "end_time": "2024-07-14T07:42:07.802064",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.792552",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Data Cleaning"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3527e534",
   "metadata": {
    "papermill": {
     "duration": 0.009184,
     "end_time": "2024-07-14T07:42:07.820928",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.811744",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Identify Spelling Errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "532300af",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.842684Z",
     "iopub.status.busy": "2024-07-14T07:42:07.842184Z",
     "iopub.status.idle": "2024-07-14T07:42:07.860551Z",
     "shell.execute_reply": "2024-07-14T07:42:07.859218Z"
    },
    "papermill": {
     "duration": 0.033223,
     "end_time": "2024-07-14T07:42:07.863680",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.830457",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Industry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Retail</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Transportation</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Consumer</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Support</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Travel</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Marketing</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Infrastructure</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Fitness</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Real Estate</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Data</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Finance</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>HR</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Food</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Product</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Media</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Education</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Other</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Energy</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Aerospace</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Logistics</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Security</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Healthcare</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Construction</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Legal</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Crypto</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Sales</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Hardware</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Manufacturing</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Software Development</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>e-commerce</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>AI</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>Semiconductors</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>Entertainment Providers</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>Telecommunications</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>Fintech</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>IT Services</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Gaming</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Business Consulting and Services</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>Motor Vehicle Manufacturing</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>Appliances</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>Social posting site</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>Insurance</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>Hospitality</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>Biotechnology Research</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>E-sport</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>SaaS</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>Translation and Localization</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>cloud</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>Environmental Services</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                            Industry\n",
       "0                             Retail\n",
       "1                     Transportation\n",
       "2                           Consumer\n",
       "3                            Support\n",
       "4                             Travel\n",
       "5                          Marketing\n",
       "6                     Infrastructure\n",
       "7                            Fitness\n",
       "8                        Real Estate\n",
       "9                               Data\n",
       "10                           Finance\n",
       "11                                HR\n",
       "12                              Food\n",
       "13                           Product\n",
       "14                             Media\n",
       "15                         Education\n",
       "16                             Other\n",
       "17                            Energy\n",
       "18                         Aerospace\n",
       "19                         Logistics\n",
       "20                          Security\n",
       "21                        Healthcare\n",
       "22                      Construction\n",
       "23                             Legal\n",
       "24                            Crypto\n",
       "25                             Sales\n",
       "26                          Hardware\n",
       "27                     Manufacturing\n",
       "28              Software Development\n",
       "29                        e-commerce\n",
       "30                                AI\n",
       "31                    Semiconductors\n",
       "32           Entertainment Providers\n",
       "33                Telecommunications\n",
       "34                           Fintech\n",
       "35                       IT Services\n",
       "36                            Gaming\n",
       "37  Business Consulting and Services\n",
       "38       Motor Vehicle Manufacturing\n",
       "39                        Appliances\n",
       "40               Social posting site\n",
       "41                         Insurance\n",
       "42                       Hospitality\n",
       "43            Biotechnology Research\n",
       "44                           E-sport\n",
       "45                              SaaS\n",
       "46      Translation and Localization\n",
       "47                             cloud\n",
       "48            Environmental Services"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inspect the Industry column \n",
    "industry = pd.read_sql_query(\"\"\"\n",
    "SELECT DISTINCT Industry\n",
    "FROM tech_layoffs;\n",
    "\"\"\",conn)\n",
    "\n",
    "industry"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4ced34b",
   "metadata": {
    "papermill": {
     "duration": 0.01155,
     "end_time": "2024-07-14T07:42:07.886118",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.874568",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Duplicate Rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "99ecc02e",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.914364Z",
     "iopub.status.busy": "2024-07-14T07:42:07.913920Z",
     "iopub.status.idle": "2024-07-14T07:42:07.949437Z",
     "shell.execute_reply": "2024-07-14T07:42:07.947589Z"
    },
    "papermill": {
     "duration": 0.052161,
     "end_time": "2024-07-14T07:42:07.953331",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.901170",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Country</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "      <th>row_num</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Criteo</td>\n",
       "      <td>Paris</td>\n",
       "      <td>France</td>\n",
       "      <td>140.0</td>\n",
       "      <td>2024-04-12</td>\n",
       "      <td>Marketing</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Etsy</td>\n",
       "      <td>New York City</td>\n",
       "      <td>USA</td>\n",
       "      <td>225.0</td>\n",
       "      <td>2023-12-13</td>\n",
       "      <td>Retail</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Tome</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>USA</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2024-04-16</td>\n",
       "      <td>AI</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Company    Location_HQ Country  Laid_Off Date_layoffs   Industry  row_num\n",
       "0  Criteo          Paris  France     140.0   2024-04-12  Marketing        2\n",
       "1    Etsy  New York City     USA     225.0   2023-12-13     Retail        2\n",
       "2    Tome  San Francisco     USA      12.0   2024-04-16         AI        2"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Identify rows that have duplicate values in all these columns. I will drop the duplicate rows later\n",
    "# Company, Location_HQ, Country, Laid_Off, Date_layoffs, Industry\n",
    "\n",
    "duplicate_rows = pd.read_sql_query(\"\"\"\n",
    "SELECT *\n",
    "FROM (\n",
    "  SELECT Company, Location_HQ, Country, Laid_Off, Date_layoffs, Industry,\n",
    "         ROW_NUMBER() OVER (PARTITION BY Company, Location_HQ, Country, Laid_Off, Date_layoffs, Industry) AS row_num\n",
    "  FROM tech_layoffs\n",
    ") AS duplicates  \n",
    "WHERE row_num > 1;\n",
    "\"\"\", conn)\n",
    "\n",
    "duplicate_rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "49017d84",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:07.983110Z",
     "iopub.status.busy": "2024-07-14T07:42:07.982656Z",
     "iopub.status.idle": "2024-07-14T07:42:08.000585Z",
     "shell.execute_reply": "2024-07-14T07:42:07.998823Z"
    },
    "papermill": {
     "duration": 0.034183,
     "end_time": "2024-07-14T07:42:08.004029",
     "exception": false,
     "start_time": "2024-07-14T07:42:07.969846",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Country</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Criteo</td>\n",
       "      <td>Paris</td>\n",
       "      <td>France</td>\n",
       "      <td>140.0</td>\n",
       "      <td>2024-04-12</td>\n",
       "      <td>Marketing</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Criteo</td>\n",
       "      <td>Paris</td>\n",
       "      <td>France</td>\n",
       "      <td>140.0</td>\n",
       "      <td>2024-04-12</td>\n",
       "      <td>Marketing</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Company Location_HQ Country  Laid_Off Date_layoffs   Industry\n",
       "0  Criteo       Paris  France     140.0   2024-04-12  Marketing\n",
       "1  Criteo       Paris  France     140.0   2024-04-12  Marketing"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inspect any of the duplicate rows\n",
    "Criteo = pd.read_sql_query(\"\"\"\n",
    "SELECT Company, Location_HQ, Country, Laid_Off,Date_layoffs, Industry\n",
    "FROM tech_layoffs\n",
    "WHERE Company LIKE 'Criteo';\n",
    "\"\"\",conn)\n",
    "\n",
    "Criteo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fb41bd25",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.032400Z",
     "iopub.status.busy": "2024-07-14T07:42:08.031021Z",
     "iopub.status.idle": "2024-07-14T07:42:08.061624Z",
     "shell.execute_reply": "2024-07-14T07:42:08.059178Z"
    },
    "papermill": {
     "duration": 0.050817,
     "end_time": "2024-07-14T07:42:08.066340",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.015523",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Country</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Etsy</td>\n",
       "      <td>New York City</td>\n",
       "      <td>USA</td>\n",
       "      <td>225.0</td>\n",
       "      <td>2023-12-13</td>\n",
       "      <td>Retail</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Etsy</td>\n",
       "      <td>New York City</td>\n",
       "      <td>USA</td>\n",
       "      <td>225.0</td>\n",
       "      <td>2023-12-13</td>\n",
       "      <td>Retail</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Company    Location_HQ Country  Laid_Off Date_layoffs Industry\n",
       "0    Etsy  New York City     USA     225.0   2023-12-13   Retail\n",
       "1    Etsy  New York City     USA     225.0   2023-12-13   Retail"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inspect another duplicate row\n",
    "Etsy = pd.read_sql_query(\"\"\"\n",
    "SELECT Company, Location_HQ, Country, Laid_Off,Date_layoffs, Industry\n",
    "FROM tech_layoffs\n",
    "WHERE Company LIKE 'Etsy'\n",
    "\"\"\",conn)\n",
    "\n",
    "Etsy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "0e7546a0",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.098781Z",
     "iopub.status.busy": "2024-07-14T07:42:08.096994Z",
     "iopub.status.idle": "2024-07-14T07:42:08.122689Z",
     "shell.execute_reply": "2024-07-14T07:42:08.117536Z"
    },
    "papermill": {
     "duration": 0.044248,
     "end_time": "2024-07-14T07:42:08.127269",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.083021",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Country</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Tome</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>USA</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2024-04-16</td>\n",
       "      <td>AI</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Tome</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>USA</td>\n",
       "      <td>12.0</td>\n",
       "      <td>2024-04-16</td>\n",
       "      <td>AI</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Company    Location_HQ Country  Laid_Off Date_layoffs Industry\n",
       "0    Tome  San Francisco     USA      12.0   2024-04-16       AI\n",
       "1    Tome  San Francisco     USA      12.0   2024-04-16       AI"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Inspect another duplicate row\n",
    "Tome = pd.read_sql_query(\"\"\"\n",
    "SELECT Company, Location_HQ, Country, Laid_Off,Date_layoffs, Industry\n",
    "FROM tech_layoffs\n",
    "WHERE Company LIKE 'Tome'\n",
    "\"\"\",conn)\n",
    "\n",
    "Tome"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5efd417c",
   "metadata": {
    "papermill": {
     "duration": 0.018809,
     "end_time": "2024-07-14T07:42:08.160803",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.141994",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# Missing Values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f876ada6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.199451Z",
     "iopub.status.busy": "2024-07-14T07:42:08.198043Z",
     "iopub.status.idle": "2024-07-14T07:42:08.233426Z",
     "shell.execute_reply": "2024-07-14T07:42:08.232079Z"
    },
    "papermill": {
     "duration": 0.064472,
     "end_time": "2024-07-14T07:42:08.241384",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.176912",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Missing values in 'Laid_Off': 162\n",
      "Missing values in 'Percentage': 172\n",
      "Missing values in 'Company_Size_before_Layoffs': 254\n",
      "Missing values in 'Company_Size_after_layoffs': 220\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Percentage</th>\n",
       "      <th>Company_Size_before_Layoffs</th>\n",
       "      <th>Company_Size_after_layoffs</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>NaN</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>NaN</td>\n",
       "      <td>100,0</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>NaN</td>\n",
       "      <td>100,0</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>45.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>111.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>31.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>109.0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>NaN</td>\n",
       "      <td>15,0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>NaN</td>\n",
       "      <td>20,0</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>NaN</td>\n",
       "      <td>100,0</td>\n",
       "      <td>None</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Laid_Off Percentage Company_Size_before_Layoffs Company_Size_after_layoffs\n",
       "0       NaN       None                        None                       None\n",
       "1       NaN      100,0                        None                         0 \n",
       "2       NaN      100,0                        None                         0 \n",
       "3      45.0       None                        None                       None\n",
       "4     111.0       None                        None                       None\n",
       "5      31.0       None                        None                       None\n",
       "6     109.0       None                        None                       None\n",
       "7       NaN       15,0                        None                       None\n",
       "8       NaN       20,0                        None                       None\n",
       "9       NaN      100,0                        None                         0 "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Missing values in Laid_Off, Percentage, Company_Size_before_Layoffs, Company_Size_after_layoffs columns\n",
    "missing_values = pd.read_sql_query(\"\"\"\n",
    "SELECT Laid_Off, Percentage, Company_Size_before_Layoffs, Company_Size_after_layoffs\n",
    "FROM tech_layoffs\n",
    "WHERE Laid_Off IS NULL\n",
    "OR Percentage IS NULL \n",
    "OR Company_Size_before_Layoffs IS NULL \n",
    "OR Company_Size_after_layoffs IS NULL;\n",
    "\"\"\",conn)\n",
    "\n",
    "for col in missing_values.columns:\n",
    "    print(f\"Missing values in '{col}': {missing_values[col].isnull().sum()}\")\n",
    "\n",
    "print() # blank line\n",
    "missing_values.head(10) # the first 10 rows"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fa7229a2",
   "metadata": {
    "papermill": {
     "duration": 0.014772,
     "end_time": "2024-07-14T07:42:08.274856",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.260084",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "# The Problem with Imputation\n",
    "\n",
    "In this case, the columns `Laid_Off`, `Percentage`, `Company_Size_before_Layoffs`, and `Company_Size_after_layoffs` are all **related**.\n",
    "\n",
    "Imagine these rows represent companies that went through layoffs.  Since we don't have all the information *(number laid off, company size before/after)*,  trying to guess those missing values would be like making up a story.  It's better to remove these rows and focus on the companies where we have complete data for a more accurate analysis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "cd5da30e",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.308992Z",
     "iopub.status.busy": "2024-07-14T07:42:08.308053Z",
     "iopub.status.idle": "2024-07-14T07:42:08.369187Z",
     "shell.execute_reply": "2024-07-14T07:42:08.367902Z"
    },
    "papermill": {
     "duration": 0.083164,
     "end_time": "2024-07-14T07:42:08.374434",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.291270",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1572, 18)\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>#</th>\n",
       "      <th>Company</th>\n",
       "      <th>Location_HQ</th>\n",
       "      <th>Region</th>\n",
       "      <th>State</th>\n",
       "      <th>Country</th>\n",
       "      <th>Continent</th>\n",
       "      <th>Laid_Off</th>\n",
       "      <th>Date_layoffs</th>\n",
       "      <th>Percentage</th>\n",
       "      <th>Company_Size_before_Layoffs</th>\n",
       "      <th>Company_Size_after_layoffs</th>\n",
       "      <th>Industry</th>\n",
       "      <th>Stage</th>\n",
       "      <th>Money_Raised_in__mil</th>\n",
       "      <th>Year</th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Tamara Mellon</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>None</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>20.0</td>\n",
       "      <td>2020-03-12</td>\n",
       "      <td>40,0</td>\n",
       "      <td>50</td>\n",
       "      <td>30</td>\n",
       "      <td>Retail</td>\n",
       "      <td>Series C</td>\n",
       "      <td>90.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>HopSkipDrive</td>\n",
       "      <td>Los Angeles</td>\n",
       "      <td>None</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>8.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>10,0</td>\n",
       "      <td>80</td>\n",
       "      <td>72</td>\n",
       "      <td>Transportation</td>\n",
       "      <td>Unknown</td>\n",
       "      <td>45.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>34.053691</td>\n",
       "      <td>-118.242766</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Panda Squad</td>\n",
       "      <td>San Francisco</td>\n",
       "      <td>San Francisco Bay Area</td>\n",
       "      <td>California</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020-03-13</td>\n",
       "      <td>75,0</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>Consumer</td>\n",
       "      <td>Seed</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>37.779259</td>\n",
       "      <td>-122.419329</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Help.com</td>\n",
       "      <td>Austin</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>16.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>100,0</td>\n",
       "      <td>16</td>\n",
       "      <td>0</td>\n",
       "      <td>Support</td>\n",
       "      <td>Seed</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>30.271129</td>\n",
       "      <td>-97.743700</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Inspirato</td>\n",
       "      <td>Denver</td>\n",
       "      <td>None</td>\n",
       "      <td>None</td>\n",
       "      <td>USA</td>\n",
       "      <td>North America</td>\n",
       "      <td>130.0</td>\n",
       "      <td>2020-03-16</td>\n",
       "      <td>22,0</td>\n",
       "      <td>591</td>\n",
       "      <td>461</td>\n",
       "      <td>Travel</td>\n",
       "      <td>Series C</td>\n",
       "      <td>79.0</td>\n",
       "      <td>2020</td>\n",
       "      <td>39.739236</td>\n",
       "      <td>-104.984862</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   #        Company    Location_HQ                  Region       State  \\\n",
       "0  1  Tamara Mellon    Los Angeles                    None  California   \n",
       "1  2   HopSkipDrive    Los Angeles                    None  California   \n",
       "2  3    Panda Squad  San Francisco  San Francisco Bay Area  California   \n",
       "3  4       Help.com         Austin                    None        None   \n",
       "4  5      Inspirato         Denver                    None        None   \n",
       "\n",
       "  Country      Continent  Laid_Off Date_layoffs Percentage  \\\n",
       "0     USA  North America      20.0   2020-03-12       40,0   \n",
       "1     USA  North America       8.0   2020-03-13       10,0   \n",
       "2     USA  North America       6.0   2020-03-13       75,0   \n",
       "3     USA  North America      16.0   2020-03-16      100,0   \n",
       "4     USA  North America     130.0   2020-03-16       22,0   \n",
       "\n",
       "  Company_Size_before_Layoffs Company_Size_after_layoffs        Industry  \\\n",
       "0                         50                         30           Retail   \n",
       "1                         80                         72   Transportation   \n",
       "2                          8                          2         Consumer   \n",
       "3                         16                          0          Support   \n",
       "4                        591                        461           Travel   \n",
       "\n",
       "      Stage  Money_Raised_in__mil  Year   latitude   longitude  \n",
       "0  Series C                  90.0  2020  34.053691 -118.242766  \n",
       "1   Unknown                  45.0  2020  34.053691 -118.242766  \n",
       "2      Seed                   1.0  2020  37.779259 -122.419329  \n",
       "3      Seed                   6.0  2020  30.271129  -97.743700  \n",
       "4  Series C                  79.0  2020  39.739236 -104.984862  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# FILTER the data, EXCLUDING rows with missing values in the specified columns\n",
    "Cleaned_tech_layoffs = pd.read_sql_query(\"\"\"\n",
    "SELECT *\n",
    "FROM tech_layoffs\n",
    "WHERE Laid_Off IS NOT NULL\n",
    "AND Percentage IS NOT NULL \n",
    "AND Company_Size_before_Layoffs IS NOT NULL \n",
    "AND Company_Size_after_layoffs IS NOT NULL;\n",
    "\"\"\",conn)\n",
    "\n",
    "print(Cleaned_tech_layoffs.shape) # 1572 clean rows remain after Filtering \n",
    "print() # blank line\n",
    "Cleaned_tech_layoffs.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "0ff050a8",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.412009Z",
     "iopub.status.busy": "2024-07-14T07:42:08.410531Z",
     "iopub.status.idle": "2024-07-14T07:42:08.430271Z",
     "shell.execute_reply": "2024-07-14T07:42:08.428327Z"
    },
    "papermill": {
     "duration": 0.042827,
     "end_time": "2024-07-14T07:42:08.433916",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.391089",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(1569, 18)\n"
     ]
    }
   ],
   "source": [
    "# Drop DUPLICATE rows from the Dataframe, based on the columns used earlier when inspecting Duplicates\n",
    "Cleaned_tech_layoffs = Cleaned_tech_layoffs.drop_duplicates(subset=['Company', 'Location_HQ', 'Country', 'Laid_Off',\n",
    "                                                                    'Date_layoffs','Industry'], keep='first') # keep first instances\n",
    "\n",
    "print(Cleaned_tech_layoffs.shape) # 1569 rows remain after dropping duplicate rows"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ce23eb22",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.462613Z",
     "iopub.status.busy": "2024-07-14T07:42:08.462129Z",
     "iopub.status.idle": "2024-07-14T07:42:08.500043Z",
     "shell.execute_reply": "2024-07-14T07:42:08.497535Z"
    },
    "papermill": {
     "duration": 0.05637,
     "end_time": "2024-07-14T07:42:08.503859",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.447489",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cleaned_tech_layoffs.csv saved.\n"
     ]
    }
   ],
   "source": [
    "# Save the cleaned DataFrame to a CSV file\n",
    "Cleaned_tech_layoffs.to_csv('Cleaned_tech_layoffs.csv', index=False)\n",
    "print('Cleaned_tech_layoffs.csv saved.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "01548e7d",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-07-14T07:42:08.531636Z",
     "iopub.status.busy": "2024-07-14T07:42:08.530983Z",
     "iopub.status.idle": "2024-07-14T07:42:08.539493Z",
     "shell.execute_reply": "2024-07-14T07:42:08.537400Z"
    },
    "papermill": {
     "duration": 0.026732,
     "end_time": "2024-07-14T07:42:08.543786",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.517054",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# Close the connection\n",
    "conn.commit()  # Save changes if any\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "687ddc43",
   "metadata": {
    "papermill": {
     "duration": 0.017494,
     "end_time": "2024-07-14T07:42:08.577156",
     "exception": false,
     "start_time": "2024-07-14T07:42:08.559662",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "\n",
    "***Working with Data, Explore Data, stay curious***"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "datasetId": 4363856,
     "sourceId": 8907976,
     "sourceType": "datasetVersion"
    }
   ],
   "dockerImageVersionId": 30732,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 7.151726,
   "end_time": "2024-07-14T07:42:09.217993",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2024-07-14T07:42:02.066267",
   "version": "2.5.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
